### ISSUE TITLE
Where is the requirements.txt?

### ISSUE THREAD

**Issue by DanielSanchezDiaz** [FlowCrypt/idn-homographs-database#11]
I just git cloned your code, cd'd into the directory made but there is no requirements.txt. Am I missing something? Is there another way to install?

**Comment by seisvelas** [comment]
Hey @DanielSanchezDiaz, great question! This package actually doesn't have any external dependencies, so there is no need to pip install anything. 

I've created a PR to remove the instruction saying pip install -r requirements.txt, that was my mistake .

Thanks a lot for pointing this out!

The two ways to install this package are:

1. `pip install homograph`, or `pip3 install homograph`
2. `python3 setup.py install` (may need to run with sudo)

If you need any additional help just let me know, glad to see this code is useful to someone else :)
