### ISSUE TITLE
More intuitive API

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/idn-homographs-database#4]
This issue is for discussing how we can make the API more intuitive and usable. From PR https://github.com/FlowCrypt/idn-homographs-database/pull/3:

> Thanks. Before we release it, we should talk about the API - I imagine is_homographic may be more obvious.

If there are any other naming, stylistic, or aesthetic issues that occur to us, we can deliberate them here, and then once we're satisfied I'll make a PR to implement all of them.

**Comment by seisvelas** [comment]
Here are the changes I intend to make so far:

homographic -> is_homographic
homoglyphic -> is_homoglyphic

**Comment by tomholub** [comment]
The distinction between homographic and homoglyphic may not be obvious. It wasn't to me (until I checked the source).

Actually, I think is_homoglyphic (checking for character likeness) would not even need to be part of external API. For this, they can use the other method and give it just one character.

Therefore there would one public method, maybe `is_homographic` (actually I'd prefer something more obvious to people like me, even if it results in longer name like `is_homographically_equivalent`, `can_be_mistaken_for`, `can_be_confused_for`, even `appears_similar` etc. Then I can use this without reading the docs or any of the terminology).

The other method like `is_char_homoglyphic` could be internal.
